name: flutter_auth
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.2
  just_audio: ^0.9.46
  country_code_picker: ^3.2.0
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_auth_web: ^5.13.8
  cloud_firestore: ^5.6.3
  image_picker: ^1.1.2
  cloudinary_public: ^0.23.1 
  js: 0.7.1
  firebase_data_connect: ^0.1.3
  google_sign_in: ^6.2.2
  encrypt: ^5.0.3
  flutter_facebook_auth_web: ^6.1.2
  flutter_secure_storage_web: ^2.0.0
  crypto: ^3.0.3
  http: ^1.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  spotify_sdk: ^3.0.2
  spotify: ^0.13.7
  url_launcher: ^6.3.1
  audio_video_progress_bar: ^2.0.3
  image: 4.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/