name: flutter_auth
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.17
  shared_preferences: ^2.2.2
  just_audio: ^0.9.36
  country_code_picker: ^3.0.0
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_auth_web: ^5.8.13
  cloud_firestore: ^5.6.3
  image_picker: ^1.0.4
  cloudinary_public: ^0.21.0 
  js: 0.6.7
  firebase_data_connect: ^0.1.3
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.3
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/